application:
    max-allowed-books: 15
    issue.max-allowed-books: 2
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/library?useSSL=false
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create